### ISSUE TITLE
Tips to increase batch size

### ISSUE THREAD

**Issue by godatta** [TaoRuijie/TalkNet_ASD#1]
Hi,

Thanks for the clean code base and the paper. I was trying to replicate your training code, and found that I can have a maximum batch size of 1500 (beyond which I face CUDA OOM error on a V100 GPU). Did you use/recommend any tips or hacks to use a batch size of 2500 for training your model?

Thanks in advance!

**Comment by TaoRuijie** [comment]
Hi,

What is the memory size of your V100? Is that 16 GB? if it is 16 I think the max batch size is about 1500. 

I used about 22GB when I set the batch size as 2500.

The batch size may affect the performance by a very minimum difference I think.

**Comment by godatta** [comment]
Thanks! Yes, the max memory size is around 14.2 GB, so may be I can do upto 1500. You are right that Performance is not getting affected, just the training time is increasing.

**Comment by TaoRuijie** [comment]
Sure that's great. I did not do experiments about batch size, so I will update the 'readme' to annotate that the batch size will not affect the performance.
