### ISSUE TITLE
关于测试集test

### ISSUE THREAD

**Issue by Overcautious** [TaoRuijie/TalkNet_ASD#11]
我进行评估test集的时候，发现结果一直都是mAP=100%，评估val集就没有问题，不知道作者有没有遇到这个问题？而且我观察到test_orig.csv文件中，所有的标签都是SPEAKING_AUDIBLE， 不知道是否和这个有关

下面是运行时的输出

`WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
 46%|███████████████████████████████████████████▏                                                  | 9814/21361 [32:11<09:59, 19.25it/s]WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.
WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.

 46%|███████████████████████████████████████████▏                                                  | 9819/21361 [32:12<17:17, 11.12it/s]WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.

 46%|███████████████████████████████████████████▎                                                  | 9834/21361 [32:14<30:59,  6.20it/s]WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.

100%|███████████████████████████████████████████████████████████████████████████████████████████| 21361/21361 [1:07:15<00:00,  5.29it/s]

mAP 100.00%`

**Comment by TaoRuijie** [comment]
这是正常的，因为test set我们没有label，你需要去官方的server给它你的预测结果来评估，我不确定现在他们的server有没有开着

We do not have the ground-truth labels for the test set, so we can not get the mAP in the test set. You need to upload your score file to AVA server. I do not know if it is open now.

Here is the link: http://activity-net.org/challenges/2021/evaluation.html

**Comment by Overcautious** [comment]
好的，谢谢回复

**Comment by Overcautious** [comment]
还想请教一个问题，ASD任务中，为什么大部分的模型对语音的操作都是MFCC处理？这是有什么原理或依据参考吗？

**Comment by TaoRuijie** [comment]
1. 在speaker recognition中大多都是用mfcc这样的频率特征处理的，所以我直接顺延了过来。 频域2D特征进model也比较方便。
2. 其实这个task我认为用时域信号也是可以的，在speech separation中time-domain的方法获得了更好的效果，所以这个task里有相似性，都是利用的时域的特征，而不是那么注重频域的特征。所以我不认为一定要用mfcc。

**Comment by TaoRuijie** [comment]
Since there is no problem, I will close this issue. Thanks
