### ISSUE TITLE
关于预训练模型的下载

### ISSUE THREAD

**Issue by Ma0110** [TaoRuijie/TalkNet_ASD#12]
你好，按照您说的命令操作后，

代码报错如下：
(pytorch) D:\project_code_home\V-A\TalkNet_ASD>python trainTalkNet.py --dataPathAVA  AVA --evaluation
Traceback (most recent call last):
  File "trainTalkNet.py", line 93, in <module>
    main()
  File "trainTalkNet.py", line 46, in main
    visualPath=os.path.join(args.visualPathAVA, 'train'), **vars(args))
  File "D:\project_code_home\V-A\TalkNet_ASD\dataLoader.py", line 95, in __init__
    mixLst = open(trialFileName).read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'AVA\\csv\\train_loader.csv'

dataPath 路径修改为相对和绝对路径，都试过，还是不行，无法下载。我是在windows平台运行的，下载预训练模型的话和我电脑有没有gpu关系不大吧？还有我的网络是可以使用google浏览器的，从github下载文件是可以的。

期待您的回应，谢谢！

**Comment by TaoRuijie** [comment]
请检查一下有没有下好csv文件到相对的路径，如果没有，注意科学上网。你需要先下载好数据和相关的csv文件

Please check if you have downloaded that CSV file to your device. You can check the 'preprocess_AVA' function in utils/tools.py

**Comment by Ma0110** [comment]
谢谢您的回复
您的意思是我只下csv文件就行是吧，比如我在tools.py中这样操作：
  download_csv(args) # Take 1 minute 
    # download_videos(args) # Take 6 hours
    # extract_audio(args) # Take 1 hour
    # extract_audio_clips(args) # Take 3 minutes
    # extract_video_clips(args) # Take about 2 days

然后再运行 python trainTalkNet.py --dataPathAVA AVA --download 
这样我就可以得到相关的csv文件，
然后再执行python trainTalkNet.py --dataPathAVA AVA --evaluation

是这样吗？
谢谢！

**Comment by TaoRuijie** [comment]
按你说的这样可以得到csv，你可以看下执行完了的output

但你需要确认你已经把AVA里的数据啥的都下下来了并且处理好了 不然有这个也没啥用

**Comment by Ma0110** [comment]
奥，我如果单纯想用这个预训练模型去做demo测试的话，我还必须要下载视频数据吗？
听你这样说的话，我只下csv文件是没用的，我必须得把300多个g的视频数据下载下来，然后处理完才可以得到预训练模型吗？
我如果自己不训练的话，只运行demoTalkNet.py，怎么获得预训练模型。

**Comment by TaoRuijie** [comment]
哦那你不需要，如果只是想用demoTalkNet, 你不需要跑trainTalkNet.py啊

请参考An ASD Demo with pretrained TalkNet model这一部分

**Comment by Ma0110** [comment]
好的，谢谢。我貌似是网络问题。
我用的是Google浏览器插件，浏览器中没问题，但在pycharm中连接失败。
谢谢老哥的耐心回答。

**Comment by Ma0110** [comment]
老哥，有预训练模型文件的下载链接嘛，我用代码中的方式实在是下载不下来了。

**Comment by TaoRuijie** [comment]
https://drive.google.com/file/d/1AbN9fCf9IexMxEKXLQY2KYBlb-IhSEea/view?usp=sharing

**Comment by Ma0110** [comment]
谢谢老哥。
