### ISSUE TITLE
missing file sfd_face.pth

### ISSUE THREAD

**Issue by season95** [TaoRuijie/TalkNet_ASD#14]
The 9th line of  'TalkNet_ASD/model/faceDetector/s3fd/__init__.py' gives the file 'sfd_face.pth' which  does not exist in 'model/faceDetector/s3fd/'.

Do i fail to find it out in this project or it just missing?

**Comment by TaoRuijie** [comment]
In line 10 to 14, there is :

```
if os.path.isfile(PATH_WEIGHT) == False:
    Link = "1KafnHz7ccT-3IyddBsL5yi2xGtxAKypt"
    cmd = "gdown --id %s -O %s"%(Link, PATH_WEIGHT)
    subprocess.call(cmd, shell=True, stdout=None)
```

Which means system will download this model if it is not exist
