### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by songhaozhen** [TaoRuijie/TalkNet_ASD#15]
国内数据集下载慢有解决的办法吗
tool.py中def extract_audio提取不了音频文件

**Comment by TaoRuijie** [comment]
第一个问题我这里没有什么解决方法。

第二个问题请提供更多的描述，我目前无法知道是你遇到的错误是什么。请提供报错截图，错误描述，已生成文件描述等。

**Comment by songhaozhen** [comment]
进行下面三步操作的时候报错
extract_audio(args) 
extract_audio_clips(args) 
extract_video_clips(args)
![QQ截图20211129215948](https://user-images.githubusercontent.com/73374369/143968154-33287cae-031d-4ba5-8c64-e2bc6d8ac79b.png)
![IMG_1312](https://user-images.githubusercontent.com/73374369/143968169-e48d8b77-e661-4766-be0e-31a6c8210ac2.PNG)

**Comment by TaoRuijie** [comment]
看起来不是处理文件错了，是你这没有文件啊好像。

extract audio失败的原因是没有找到本身的video文件。clip video的原因也是这个

这个orig_audios/trainval里有没有2fwni...wav这个文件，因为你之前提取audio就错了，所以不能clip它。

可以考虑如下：
1. 这里你的路径应该也是有问题的，第一个截图报错是因为找不到那个路径无法建立文件夹，需要检查对齐，或者你可以直接使用绝对路径
2. 检查第一步需要下载的video文件是否存在，我觉得你没有下好或者只下载了部分，那没有这个当然没法提取了。

**Comment by songhaozhen** [comment]
下的实在太慢了我就下了部分，我修改了list文件和csv文件的视频数量也不可以吗，video文件在那个文件夹下是存在的
我去试试绝对路径

**Comment by TaoRuijie** [comment]
可以，但要确定那些文件本身下了下来并且你处理的每个都是完整的。并且你的csv和list文件里用到的都要已经下载完成。

那可能就是路径的问题，确保对齐

**Comment by songhaozhen** [comment]
好的，多谢大佬指导！

**Comment by songhaozhen** [comment]
我找到问题了，windos系统下文件名称不能带有英文冒号。。。
