### ISSUE TITLE
Missing License file

### ISSUE THREAD

**Issue by eek** [TaoRuijie/TalkNet_ASD#19]
Hi @TaoRuijie, we love the work that you have done and that you posted it as open-source, can you also add a license file to the repository that states the open-source license the project should have? MIT would be great. 

Thanks!

**Comment by TaoRuijie** [comment]
Hi, I have added it. I am glad that project is useful.

**Comment by eek** [comment]
It is useful! You have done an excellent job! Congrats and thanks again!
