### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by simonzfei** [TaoRuijie/TalkNet_ASD#20]
Thank you for sharing your code and models
Could you share your Google Cloud Disk link？
Thanks very much!

**Comment by TaoRuijie** [comment]
Here I only have the link for the csv files and the pretrain model. I already put it in the code, while you can also find these files in the following link:

https://drive.google.com/drive/folders/16TuXli9F_HTQ4UetrB68tp6UUSntXPR5?usp=sharing

The dataset is very big, so I can not provide the entire dataset in google driver. However, you can find the data download and preprocessing code in this project, it is automatic.
