### ISSUE TITLE
"List index out of range" error during evaluation

### ISSUE THREAD

**Issue by xiang-burlington** [TaoRuijie/TalkNet_ASD#22]
Thanks for sharing your excellent work! Your code is really friendly and easy to use.

While evaluating the performance of pre-trained model with command: python trainTalkNet.py --dataPathAVA AVADataPath --evaluation.

For the context, I downloaded the required data but hadn't trained a model -- guess it's not necessary since we are using downloaded pre-trained model here.

The I got the following error message:

Downloading...
From: https://drive.google.com/uc?id=1NVIkksrD3zbxbDuDbPc_846bLfPSZcZm
To: /home/xiangdong/experiment/TalkNet_ASD/pretrain_AVA.model
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.2M/63.2M [00:20<00:00, 3.10MB/s]
12-23 12:26:36 Model para number = 15.01
Model pretrain_AVA.model loaded from previous state!
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8015/8015 [14:50<00:00,  9.00it/s]
Traceback (most recent call last):
  File "trainTalkNet.py", line 86, in <module>
    main()
  File "trainTalkNet.py", line 52, in main
    mAP = s.evaluate_network(loader = valLoader, **vars(args))
  File "/home/xiangdong/experiment/TalkNet_ASD/talkNet.py", line 75, in evaluate_network
    mAP = float(str(subprocess.run(cmd, shell=True, capture_output =True).stdout).split(' ')[2][:5])
IndexError: list index out of range

**Comment by TaoRuijie** [comment]
It looks like most of the part is correct, this 'cmd' is using the official code to evaluate, and I do '.split(' ')[2][:5]' to extract the mAP value only. It looks like the output is incorrect.

Could you do this cmd directly to see the output? Such as `python -O utils/get_ava_active_speaker_performance.py -g evalOrig -p evalCsvSave`. Notice use the path of the evalOrig and evalCsvSave here.

If it is correct, you ought to get sth like "average precision: 9*.**"

**Comment by xiang-burlington** [comment]
Hi Ruijie,

Thanks for the prompt reply, it solved the problem. get_ava_active_speaker_performance.py works, I got a mAP of 92.28%.

Also after I changed the code 
mAP = float(str(subprocess.run(cmd, shell=True, capture_output =True).stdout).split(' ')[2][:5])
to
mAP = float(str(subprocess.run(cmd, shell=True, capture_output =True).stdout).split(')[2][:5])
"python trainTalkNet.py --dataPathAVA AVADataPath --evaluation." worked as well. I guess it is a version issue of python.
