### ISSUE TITLE
FileNotFoundError After Running python demoTalkNet.py --videoName 001 Command

### ISSUE THREAD

**Issue by Cuecute** [TaoRuijie/TalkNet_ASD#23]
Thank you for sharing your work.

I tried an ASD Demo with pretrained TalkNet model.
After I ran the command "python demoTalkNet.py --videoName 001",
I got the message "FileNotFoundError: [Errno 2] No such file or directory: 'demo\\001\\pycrop\\demo\\001\\pycrop\\00000.wav'"

** I used only CPU so I had changed the codes in demoTalkNet.py and talkNet.py by replacing all 'cuda' words to 'cpu' and replaced line 83 in talkNet.py into loadedState = torch.load(path,map_location=torch.device('cpu')) then I ran the command "python demoTalkNet.py --videoName 001
![Capture](https://user-images.githubusercontent.com/92107544/147382780-56623cd1-e320-4286-b6d9-f9450a5bec1b.PNG)
"

**Comment by TaoRuijie** [comment]
You are using windows, notice that the path ought to be splitted by '//' instead of '\'

**Comment by Cuecute** [comment]
Thank you very much :)
