### ISSUE TITLE
Suggestion for adding face recognition in this project

### ISSUE THREAD

**Issue by Cuecute** [TaoRuijie/TalkNet_ASD#25]
Hello. I want to add face recognition in this project. Could you give me some advice what parts of this project need to be modified or added.

Thank you in advance.

**Comment by Cuecute** [comment]
Especially in the demo code that input/output video result - demoTalkNet.py

**Comment by TaoRuijie** [comment]
Sorry I am not familar with that part.

From what I know, Insightface might be a good choice for face recognition,here is the link: https://github.com/deepinsight/insightface, it is user friendly.

For the demo part, I geuss you can use the cropped face videos as the input for the face recognition model.

**Comment by Cuecute** [comment]
thank you very much :)
