### ISSUE TITLE
TalkSet data

### ISSUE THREAD

**Issue by junwenxiong** [TaoRuijie/TalkNet_ASD#26]
Thank you for doing such an excellent job. Currently I want to train a model on TalkSet, and have already processed voxceleb2 and lrs3 in accordance with the proposed generate_talkset code, but i lack the dataloader code for this part. Could you please share it?

**Comment by TaoRuijie** [comment]
Please check here: https://github.com/TaoRuijie/TalkNet_ASD/issues/4#issuecomment-889714345

**Comment by junwenxiong** [comment]
Thank you for clear explanation!
