### ISSUE TITLE
Talk Dataset

### ISSUE THREAD

**Issue by xiejiachen** [TaoRuijie/TalkNet_ASD#27]
As I am working inside China mainland, it is not easy to download with the script given
`python trainTalkNet.py --dataPathAVA AVADataPath --download `

It seems the script does not check the related files exist or not, each time it just re-download all file?
Is there any better way to fix it?

**Comment by TaoRuijie** [comment]
Er...I did not consider this issue. Just can provide some ideas:

Please check the code in https://github.com/TaoRuijie/TalkNet_ASD/blob/main/utils/tools.py, L35, annotate the commends that you has finished. 

You can add the lines such as : "if os.exist(file) == False: download_file" to save time.

**Comment by xiejiachen** [comment]
> Er...I did not consider this issue. Just can provide some ideas:
> 
> Please check the code in https://github.com/TaoRuijie/TalkNet_ASD/blob/main/utils/tools.py, L35, annotate the commends that you has finished.
> 
> You can add the lines such as : "if os.exist(file) == False: download_file" to save time.

Solved, Thanks

**Comment by shhuangcoder** [comment]
> As I am working inside China mainland, it is not easy to download with the script given

How did you download the dataset?
