### ISSUE TITLE
Could you plz explain details meaning of csv file.

### ISSUE THREAD

**Issue by xiejiachen** [TaoRuijie/TalkNet_ASD#30]
I saw there are a lot of array looks like [1,1,1,1,1,1,1,1,1] and a big number like 21231 after with that, within test_loader.csv

And there are a lot of id, such as video id, instance id, entity id, and label id.

I guess video id is the clip_figure accompanied id with each related video, and entity_box_x,y is the face clip marks, but what are the meanings of the others' id?
Could you please give more details ?

Really Thanks!

**Comment by TaoRuijie** [comment]
The official description can be found here:
https://research.google.com/ava/download.html#ava_active_speaker_download
Instance is the name of the video, entity is the name of the clips (One video has many clips)

[1,1,1...1] is the label(1 for active, 0 for non-active). Test data does not have the label. So all the labels are 1. 

The number is the length of the labels for the clip I think.

**Comment by xiejiachen** [comment]
Dear Tao:
For an example, there is a line from val_loader.csv such as 
HV0H6oc4Kvs_0960_1020:1	10	25.0	[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, ]	2715

where
HV0H6oc4Kvs_0960_1020:1  is the instance_id
10 is frames
25.0 is what?
[0,0,0,0,...,1] is label_id
2715 is what?

Thanks!

**Comment by TaoRuijie** [comment]
25.0 is fps, notice that the fps is not always 25.0 in AVA.

2715 is the random index, you can ignore that part. That is not important. Sorry forget to mention it.

**Comment by xiejiachen** [comment]
> 

Thanks
