### ISSUE TITLE
audio input size

### ISSUE THREAD

**Issue by Falmi** [TaoRuijie/TalkNet_ASD#32]
Thanks for the contribution. From your paper the input image size is 128x128 and the dimension of MFCC is 13. what is the size of the MFCC is the temporal direction? I am asking this cause your code inputs different MFCC size at each interaction. How the network managed to input different audio input at each iteration I was expect uniform input size for the audio network.

**Comment by TaoRuijie** [comment]
The length of MFCC is depend on the length of input. For instance, fps=25, the 1 second audio will lead to the MFCC of (100,13), 100 is the length. If 2-second, the MFCC is 200.

https://github.com/TaoRuijie/TalkNet-ASD/blob/main/FAQ.md， You can check here, 1.2 for the variable length input.

In general, the length of input in each mini-batch is the same, while different in different mini-batch.

**Comment by Falmi** [comment]
Thanks,

**Comment by Falmi** [comment]
which means the audio embedder accepts different audio input sizes at different iterations which is number_of_image*4, and output shape of (batch,number_of_images,128), right?

**Comment by TaoRuijie** [comment]
let's say you have N video frames.

The shape of audio input is (13, 4 * N), the shape of visual input is (H, W, 3, N). H=W.
The shape of audio encoder output is (512, N), the shape of visual encoder output is (512, N).

Is that clear?

**Comment by Falmi** [comment]
yes, I got it but in your code, you used 128 output channels, right?. And, both encoders accept different input sizes at different iterations based on the length of input video, right? Thanks!

**Comment by TaoRuijie** [comment]
sorry I remember it incorrectly. Yes it is 128, 

Yes correct, 
For instance, 1st iteration, video length is 25 frames, input audio length is 100, input visual length is 25
2st iteration, video length is 50 frames, input audio length is 200, input visual length is 50.

**Comment by Falmi** [comment]
Hi Tao, How did you handle the audio input size when the input image length is 1.  Assume the video is 25fps, and the subject/person only appears once through the 1-second clip.

**Comment by TaoRuijie** [comment]
for 1-second video, audio length is 16000 with length of MFCC equal to 100, the audio embedding length is 25. Visual embedding length is 25. I guess you are asking that?

**Comment by Falmi** [comment]
let me make it clear, what is the minimum input audio length in seconds.

**Comment by TaoRuijie** [comment]
Any input length > 1 video frame can. 

While min length for training is one second in my experiments, too short can not work well I guess.

**Comment by Falmi** [comment]
Thanks, how do you handle the input audio if you could get this kind of input size during training HV0H6oc4Kvs_0960_1980:1 1 25.0 [0] 271

**Comment by TaoRuijie** [comment]
In AVA, no these length setting. Just put training data into model

I mean for TalkSet, length min is 1s.

**Comment by Falmi** [comment]
Okay, you trained the model with >1sec input and tested it on variable-length input, right?

**Comment by TaoRuijie** [comment]
No, I mean in AVA, Based on the data itself, the whole length is used

**Comment by Falmi** [comment]
which means you can take an input frame which >=1, right?

**Comment by TaoRuijie** [comment]
yes
