### ISSUE TITLE
request for clarification on evaluation code

### ISSUE THREAD

**Issue by Falmi** [TaoRuijie/TalkNet_ASD#34]
Hi Tao, Could you explain why you added only " Speaking_Audible"  to the prediction CSV file after prediction https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/talkNet.py#L66
I would be glad if you could explain the evaluation logic you used in your code. Thanks!

**Comment by TaoRuijie** [comment]
Because the official toolkit only use the score to compute the metrics, and only compute the score with the label 'SPEAKING_AUDIBLE'.

See here: https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/utils/get_ava_active_speaker_performance.py#L112

And here:
https://github.com/fuankarion/active-speakers-context/issues/17

When I first do that work. I do not know that and mark the prediction labels, then a low mAP will obtain.

**Comment by Falmi** [comment]
I see, thanks! But I couldn't find in your code where you used the score for evaluation purposes. If I'm not wrong you just compare the prediction evaluation label you generated using the above-mentioned line of code against the ground truth(https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/utils/get_ava_active_speaker_performance.py#L156). Could you mention the line of code you used the score to identify the correct prediction? Thanks.

**Comment by TaoRuijie** [comment]
This is not my code, this is the official toolkit, I did not study it for details.

See here: https://github.com/activitynet/ActivityNet/blob/master/Evaluation/get_ava_active_speaker_performance.py

**Comment by Falmi** [comment]
Thanks, I will read it by myself.

**Comment by adhiraj2001** [comment]
@Falmi Hey, did you figure this out ?

Even after looking at the official toolkit, I don't understand how `score` is incorporated into the evaluation, it only seems to be used to sort the Dataframe `df_merged`:
```python
df_merged = df_groundtruth.merge(
      df_predictions,
      on="uid",
      suffixes=("_groundtruth", "_prediction"),
      validate="1:1").sort_values(
          by=["score"], ascending=False).reset_index()
```

But the `score` doesn't seem to be taken into consideration while calculating `tp` (or anything else):
```python
# Populates each row with 1 if this row is a true positive
  # (at its score level).
  df_merged["is_tp"] = np.where(
      (df_merged["label_groundtruth"] == "SPEAKING_AUDIBLE") &
      (df_merged["label_prediction"] == "SPEAKING_AUDIBLE"), 1, 0)
```

I apologize @TaoRuijie for making this old issue active again and if I am missing something obvious.
