### ISSUE TITLE
Clarification on image normalization.

### ISSUE THREAD

**Issue by Falmi** [TaoRuijie/TalkNet_ASD#35]
Hi Tao,

Could you explain the normalization technique you used and these numbers the, 0.4161 and 0.1688?  Thanks!
https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/model/talkNetModel.py#L32

**Comment by TaoRuijie** [comment]
See here https://github.com/lordmartian/deep_avsr/blob/256c9c94aac5d8dd79a61c06d58b75d7d74c6e9e/video_only/config.py#L39
