### ISSUE TITLE
Talkset数据集中损失比较大

### ISSUE THREAD

**Issue by coreeey** [TaoRuijie/TalkNet_ASD#38]
大佬你好，请问你在训练talkset数据集时，训练集的损失大吗？我发现我在训练的时候loss最低也就只能下降到0.8，但使用其他数据集的时候往往都能下降到0.2，请问这种情况正常吗？

**Comment by TaoRuijie** [comment]
这个我当时的log文件都没有存，不太记得了这个。主要还是看performance吧和loss关系不是很大我记得

**Comment by coreeey** [comment]
好的 谢谢，请问您还记得Talkset数据集训练了多少轮才有论文的精度吗？

**Comment by TaoRuijie** [comment]
应该是和ava差不多 没有train多久

**Comment by coreeey** [comment]
我训练大概30轮，验证集mAP能达到92%，但是使用AVA/Talkies数据集测试的时候，效果都不太好，只有70左右，更换了人脸检测算法之后，仍没有改进，同时使用demotalknet.py测试其他vlog的时候发现结果也不太好，请问大佬觉得可能是什么原因导致的吗？是否是训练轮数太少了？

**Comment by TaoRuijie** [comment]
如果你用talkset训练 不要再ava test。 ava的人脸detect很拉跨，不能匹配的。

不过demo出来的结果还不好那说明你Train的模型有点问题啊。我记得我train了20个epoch就是demo里的pretrain_talkset模型了，效果还可以。

注意train在talkset的时候face encoder那个resnet18我用的应该是一个pretrain的模型 这一点可以看一下。

**Comment by coreeey** [comment]
非常感谢大佬的耐心回答，我发现我的TFAudio没有被新生成的txt覆盖，导致标签匹配出了问题。
