### ISSUE TITLE
talknet训练时minibatch中读取的数据，为什么每次只是从audioFeature， visualFeature， labels取第一个 ？这样不就相当于每次只拿一条视频来训练么 ？

### ISSUE THREAD

**Issue by Ontheway361** [TaoRuijie/TalkNet_ASD#39]

**Comment by TaoRuijie** [comment]
不是的，请看这里。 F&Q里的1.2 How to figure the variable length of data during training ?

**Comment by Ontheway361** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    不是的，u see ur code, let code say something.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2459699580
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Tao ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年09月8日 16:07
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [TaoRuijie/TalkNet-ASD] talknet训练时minibatch中读取的数据，为什么每次只是从audioFeature， visualFeature， labels取第一个 ？这样不就相当于每次只拿一条视频来训练么 ？ (Issue #39)
        
      
    
  
  

不是的，请看这里。 F&Q里的1.2 How to figure the variable length of data during training ?



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Ontheway361** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Yeah, u are right, I’m fool.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2459699580
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年09月8日 16:41
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              回复： [TaoRuijie/TalkNet-ASD] talknet训练时minibatch中读取的数据，为什么每次只是从audioFeature， visualFeature， labels取第一个 ？这样不就相当于每次只拿一条视频来训练么 ？ (Issue #39)
        
      
    
  
  
    
    不是的，u see ur code, let code say something.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2459699580
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            Tao ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2022年09月8日 16:07
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [TaoRuijie/TalkNet-ASD] talknet训练时minibatch中读取的数据，为什么每次只是从audioFeature， visualFeature， labels取第一个 ？这样不就相当于每次只拿一条视频来训练么 ？ (Issue #39)
        
      
    
  
  

不是的，请看这里。 F&Q里的1.2 How to figure the variable length of data during training ?



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。
