### ISSUE TITLE
Getting NaN values for prediction

### ISSUE THREAD

**Issue by AdhamKhalifa** [TaoRuijie/TalkNet_ASD#41]
Hello everyone,

Thank you so much for sharing the code. It was so helpful. I was using the pre-trained model on a video, and I can tell that it can smoothly detect all faces, but it highlights them all in red color (not-speaking), and it doesn't show a number for prediction. It simply shows a NaN error. Do you know what could be wrong?

Image attached: [https://i.imgur.com/ssgjjP0.png](url)

**Comment by TaoRuijie** [comment]
It looks strange, did you just run the demoTalkNet.py code directly? It looks like model get the bug for processing the videos, so the prediction score becomes NaN.

**Comment by AdhamKhalifa** [comment]
Hello,

Yes, I just run that python file and get this error. I simply run:
`python demoTalkNet.py --videoName {video name without extension}`
It keeps detecting scenes and faces and generating crop pictures, and here's the log:

`2022-11-12 01:27:11 Extract the video and save in demo\video4\pyavi\video.avi
2022-11-12 01:27:12 Extract the audio and save in demo\video4\pyavi\audio.wav
2022-11-12 01:27:28 Extract the frames and save in demo\video4\pyframes
demo\video4\pyavi\video.avi - scenes detected 3
2022-11-12 01:28:38 Scene detection and save in demo\video4\pywork
2022-11-12 01:32:40 Face detection and save in demo\video4\pywork
2022-11-12 01:32:40 Face track and detected 102 tracks
100%|████████████████████████████████████████████████████████████████████████████████| 102/102 [01:02<00:00,  1.62it/s]
2022-11-12 01:33:43 Face Crop and saved in demo\video4\pycrop tracks
11-12 01:33:43 Model para number = 15.01
Model pretrain_TalkSet.model loaded from previous state!
  0%|                                                                                          | 0/102 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "demoTalkNet.py", line 458, in <module>
    main()
  File "demoTalkNet.py", line 444, in main
    scores = evaluate_network(files, args)
  File "demoTalkNet.py", line 218, in evaluate_network
    _, audio = wavfile.read(os.path.join(args.pycropPath, fileName + '.wav'))
  File "C:\Users\Adham\miniconda3\envs\TalkNet\lib\site-packages\scipy\io\wavfile.py", line 647, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'demo\\video4\\pycrop\\demo\\video4\\pycrop\\00000.wav'`

As you can see, it didn't generate the video_out file. Do you know what it could be?

**Comment by AdhamKhalifa** [comment]
Also that FileNotFoundError is confusing because that .wav file exists but in pycrop directory. I don't know why it repeats the demo\\video4\\pycrop

**Comment by TaoRuijie** [comment]
you are using windows, the delimiter is different with linux. 

\ and //

**Comment by AdhamKhalifa** [comment]
So how do you think I should fix it?

**Comment by TaoRuijie** [comment]
You need to use the correct windows-based absolute path.
