### ISSUE TITLE
About real-time detection

### ISSUE THREAD

**Issue by henrycjh** [TaoRuijie/TalkNet_ASD#42]
Hi @TaoRuijie,
Thanks for your great work! 
I am trying to use the TalkNet with Webcam, and I notice that you have mentioned that it is possible #7 
Unfortunately, I can not figured out what you mean in that issue. Could you please give me some suggestion on how to modify the code in demoTalkNet.py?
By the way, my idea is that we could feed the input stream into the model every 2 seconds, though this would make it delay for 2 seconds. How do you think about it?
Thanks for your attention!

**Comment by TaoRuijie** [comment]
Sorry I am not very sure since I did not try until now (have plan to try this later), but I think what you mentioned looks reasonable? Ar...Sorry I think there are might many details need to solve, current I do not have a perfect idea.

**Comment by henrycjh** [comment]
Thanks for your reply! I would have try to do it later and let you know if there is any progress.

**Comment by hugoobui** [comment]
Hello, I'm also trying to make it work on my camera. Any progress or tips ?
