### ISSUE TITLE
Bug in audio loss computation?

### ISSUE THREAD

**Issue by SAGNIKMJR** [TaoRuijie/TalkNet_ASD#47]
Hi @TaoRuijie,

You have an audio classifcation loss in https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/talkNet.py#L36, and the labels that you use there are the ASD labels (which basically say if the voice matches the face or not). However, it's not possible to predict just on the basis of audio which face is speaking since there is no concept of speaker classes that's uniform/consistent throughout the dataset. Shouldn't the labels be voice-activity labels instead, i.e. one should first check if for the particular frame any of the visible faces is an active speaker and if that's the case, assign the frames a label of 1 and 0 otherwise?

**Comment by TaoRuijie** [comment]
Yes this setting is same to the baseline paper (AVA dataset paper by Google)

I also tried to remove nlossA and nlossV, the results are similar.
