### ISSUE TITLE
Question about window length and hop size for spectrogram

### ISSUE THREAD

**Issue by DevKiHyun** [TaoRuijie/TalkNet_ASD#48]
Hi!
Thanks to good repo.

I wonder that why you adjust window and hop size based on fps value?

Of course, I also think that is not critical issue and good choice.

But, from an audio point of view, even if fps changes everytime, but audio was recorded with fixed sampling rate like 16k.

So, I think, we can convert  audio with just fix window length (ex. 25ms) and hop length (ex. 16ms).

thanks to read my question.

**Comment by TaoRuijie** [comment]
Audio and visual are independent. Usually 25fps video and 16KHz audio sampling rate. But if a video is 30pfs, sampling rate can also be 16000HZ.

**Comment by DevKiHyun** [comment]
@TaoRuijie 
Thanks to answer me.

So, why you choose variable window length and hop size? just to control sequence length of mfcc?
if we change the window size and hop size, then context size of each frame is change too, right?

**Comment by TaoRuijie** [comment]
Yes correct. 

To make sure model can handle different sampling rate audio

**Comment by DevKiHyun** [comment]
Okay, and then, can I fix window size and hop?

**Comment by DevKiHyun** [comment]
Okay. this code [https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/dataLoader.py#L41](url)
is to handle different sampling rate audio? But, I think that it is just handle difference fps not sampling rate.
Why we need to control sequence length of mfcc based on fps? 

Follow your code, we  just aim to only fit 4x the number of video frames as a result. Whatever the mfcc length is.


Sorry for not understanding yet.

**Comment by DevKiHyun** [comment]
Moreover, if the mfcc length is over num_frames  * 4 (== actually, num_frames  is video frames). You cut the mfcc. It is okay?
This can be information losing. But, i also run your training code. It works well. But, just  my wonder.

**Comment by TaoRuijie** [comment]
> Okay. this code [https://github.com/TaoRuijie/TalkNet-ASD/blob/85b37afc32bedcadd8b5dfbc7f69298a76de279b/dataLoader.py#L41](url) is to handle different sampling rate audio? But, I think that it is just handle difference fps not sampling rate. Why we need to control sequence length of mfcc based on fps?
> 
> Follow your code, we just aim to only fit 4x the number of video frames as a result. Whatever the mfcc length is.
> 
> Sorry for not understanding yet.

Yes you can, only make sure "4x the number of video frames".

**Comment by TaoRuijie** [comment]
> 

The reason is that mfcc is more “fine-grained”, for instance for 25 video frames, the length of audio can be 100mfcc, 101 mfcc or even 102 mfcc. Cut a bit will not effect the performance

**Comment by iaaidev2** [comment]
video frame_rate = 29.97002997002997, how can I solve this problem? @TaoRuijie
