### ISSUE TITLE
Minimum length of the audio and video feature

### ISSUE THREAD

**Issue by rosebbb** [TaoRuijie/TalkNet_ASD#50]
At line 233 in demoTalkNet.py, should it be: 
``length = min((audioFeature.shape[0] - audioFeature.shape[0] % 4) / 100, videoFeature.shape[0]/25)``
as the first term is computing length of audio in seconds?

Thanks!

**Comment by TaoRuijie** [comment]
Ar yes, thanks for point out. You are correct.
