### ISSUE TITLE
Question about repeated calls to the model by using same duration multiple times in parameter durationset

### ISSUE THREAD

**Issue by gomingchen** [TaoRuijie/TalkNet_ASD#51]
Hi Ruijie,

Thank you for the excellent work! I have a quick question. I see that durationSet's value is 
`durationSet = {1,1,1,2,2,2,3,3,4,5,6} # Use this line can get more reliable result`
in Line 215 in demoTalkNet.py. What it does is repeat the prediction of 1 sec's data 3 times, and 2 sec's data 3 times, etc. Eventually, all scores are averaged. Please correct me if I am wrong.
I am a newbie to segmentation/object detection models. What's the meaning of repeating the run three times? Aren't the weights of the model all definitive numbers? Does each of the three runs of the model provide different results using the same 1-sec (or 2-sec, ..., etc) data segments? If so, what caused different results?

Thank you very much!!

Best,
Chen

**Comment by TaoRuijie** [comment]
That is just used to make the system more robust, like multiple window, each window gets a short segment, then average the results

**Comment by gomingchen** [comment]
Hi Ruijie,

Thank you very much for your reply. Another question, is the number labeled on top of each face, so-called "score" actually loss? They are `nloss` in lossAV.forward, right? Thank you! Best, Chen

**Comment by TaoRuijie** [comment]
Similar but not totally the same, sorry for missing your information
