### ISSUE TITLE
About ColumbiaASD dataset 

### ISSUE THREAD

**Issue by Ontheway361** [TaoRuijie/TalkNet_ASD#52]
Hi，RuiJie老铁，你好，想咨询一下你关于ColumbiaASD数据集的一些细节，标注链接在这里，http://www.jaychakravarty.com/wp-content/uploads/2016/02/columbiaDatasetGroundTruth.zip，对应的readme.txt截图如下
![image](https://github.com/TaoRuijie/TalkNet-ASD/assets/32952060/11a37868-9ecb-4927-b42f-62b14f9454aa)
   我在做可视化的时候，发现位置框根本就对应不起来，以tracks_25000_35000中的0.txt【25472	0	48	143	0】 、1.txt【25472	226	40	153	1】中framename为25472的行为例;
![image](https://github.com/TaoRuijie/TalkNet-ASD/assets/32952060/f6e2f79a-3199-4ce4-9df6-47a9933a2bd6)
想问下你当初处理数据的时候，是否有遇到同样的问题 ？

**Comment by TaoRuijie** [comment]
你好，视频分辨率你下的和他下的不一样 对着按比例调整下就好了

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。

**Comment by wqvbjhc** [comment]
@Ontheway361 
您好，请问比例调整好了吗，能否告知下具体比例数值。

**Comment by Ontheway361** [comment]
您好，我已经收到您的邮件，谢谢。
