### ISSUE TITLE
Demo with Visualization

### ISSUE THREAD

**Issue by mvoodarla** [TaoRuijie/TalkNet_ASD#55]
Hey folks - I really love this model so I made a demo and put it up here! Feel free to try it for yourself. Also made a few changes that would return consistent frame numbers regardless of input frame rate, etc.

https://www.sievedata.com/functions/sieve/talknet-asd

P.S. I work at this company [Sieve](https://sievedata.com/) that works on video and audio AI.

**Comment by TaoRuijie** [comment]
Thanks bro! This demo page is cool. Appreciate for your contribution!

I will also consider adding this demo page for better representation in my future work.

By the way, I have checked your company website. Great work :)

**Comment by mvoodarla** [comment]
Amazing! Glad you like it. You should be able to deploy and make these demos yourself in the future pretty easily by just signing up and following the instructions :)

**Comment by ShunyaYamagami** [comment]
@TaoRuijie 
Thank you for sharing!
Is the pre-trained model used in this demo identical to the one described in the README?
I feel that the output results I have tried locally and with Sieve are too different.
