### ISSUE TITLE
Can I use less FPS to make things done?

### ISSUE THREAD

**Issue by kaka1909** [TaoRuijie/TalkNet_ASD#57]
Thank you for the wonderful job firstly. 

I read the code and found you use 25 as the FPS to fetch frames and compute. But for long video, 25 fps is kind of too many, I want to reduce the fps to 10 to accelerate the process (of course it will deduct some accuracy). I find many "25" in the project, I don't know if I can simply replace all "25" with "10" or "15"?

**Comment by TaoRuijie** [comment]
I think...cannot. Model is trained for 25 fps, if you change to 10 fps, I suggest you upsample the visual frames into 25 fps first...
