### ISSUE TITLE
can I change the ffmpeg commands to opencv

### ISSUE THREAD

**Issue by mhmd-mst** [TaoRuijie/TalkNet_ASD#59]
Hello, Thanks a lot for this work, I want to ask you:

1.  is it possible to run for the frame extraction opencv instead.
2. can I use the original mp4 format instead of avi, 

I am not sure the 2nd question is necessary but I am working on another model alongside this which preferably run with opencv which leads to different frame number than TalkNet. so I need them to work on equal number of frames so I can join there outputs.

**Comment by TaoRuijie** [comment]
1. Yes opencv can also extract frames
2. Yes, in my demo, input can be mp4 or avi, the output is avi, while you can also change the output into mp4
