### ISSUE TITLE
How can I train the network with TalkSet?

### ISSUE THREAD

**Issue by bugdary** [TaoRuijie/TalkNet_ASD#6]
Hi
Thanks a lot for sharing your code :)
I must have missed something - how can I train the network using TalkSet? Is it the same procedure ?

Thanks !

**Comment by TaoRuijie** [comment]
Hi,

Have you generated TalkSet?

If you have got that dataset, I think the only difference is in data loader, you can check here: https://github.com/TaoRuijie/TalkNet_ASD/issues/4#issuecomment-889714345. I provided our dataloader code here.

For the other parts, I think there is no difference.

**Comment by bugdary** [comment]
should I pre-process the Voxceleb and the LRS datasets ?

**Comment by TaoRuijie** [comment]
I write the readme file in here[https://github.com/TaoRuijie/TalkNet_ASD/tree/main/TalkSet], you can check my description to generate this TalkSet.

**Comment by TaoRuijie** [comment]
Yes, you need to prepare VoxCeleb and LRS3 first. Because I just modify these two datasets to generate TalkSet. So I cannot release it.

**Comment by bugdary** [comment]
Thanks !
