### ISSUE TITLE
关于将代码移植到windows系统的问题

### ISSUE THREAD

**Issue by JOKER-rf** [TaoRuijie/TalkNet_ASD#60]
大佬您好，我想问一下，就是在windows系统里不允许文件名里有冒号，有什么比较好的解决办法，我自己尝试过在生成视频切片文件的时候把entity_id的冒号split出来换成'.'，但是他的vedioclips少了10个G，然后在后面dataloader的时候也把dataname中的冒号在代码里换成了'.'，然后运行trainTalkNet.py，结果是他有训练的进度条，但是score.txt里没有记录内容，而且训练完一个epoch之后他会如下显示：
Traceback (most recent call last):
  File "G:\TalkNet\TalkNet-ASD-main\trainTalkNet.py", line 86, in <module>
    main()
  File "G:\TalkNet\TalkNet-ASD-main\trainTalkNet.py", line 75, in main
    mAPs.append(s.evaluate_network(epoch = epoch, loader = valLoader, **vars(args)))
  File "G:\TalkNet\TalkNet-ASD-main\talkNet.py", line 76, in evaluate_network
    mAP = float(str(subprocess.run(cmd, shell=True, capture_output =True).stdout).split(' ')[2][:5])
IndexError: list index out of range
我把subprocess.run(cmd, shell=True, capture_output =True).stdout直接print出来后是这样的：b''

**Comment by TaoRuijie** [comment]
抱歉漏看信息了 这个问题没遇到过呐一直用的linux

首先如果换的话 要保证TXT文件和视频文件等全都要换对啊，其次感觉不能换成.吧，这样换成-或者_这样的吧
