### ISSUE TITLE
Update to PySceneDetect 0.6 - change from VideoManager to open_video

### ISSUE THREAD

**Issue by pingaaron** [TaoRuijie/TalkNet_ASD#62]
In SceneManager, VideoManager has been deprecated. I changed some of the code in the demo program (demoTalkNet.py) to reflect the change and am sharing it back here. It is not a very big change, actually. We are supposed to use "open_video" now instead of the the VideoManager class.

    video = open_video(args.videoFilePath)
    sceneManager = SceneManager(StatsManager())
    sceneManager.add_detector(ContentDetector())
    video.seek(args.start)
    sceneManager.detect_scenes(frame_source = video)

There is a migration guide here:
https://www.scenedetect.com/docs/latest/api/migration_guide.html

**Comment by TaoRuijie** [comment]
Yes I notice that issue, thanks for your information!
