### ISSUE TITLE
关于视频FPS的问题

### ISSUE THREAD

**Issue by wanghuii1** [TaoRuijie/TalkNet_ASD#64]
因为AVA数据集fps是可变的，train_loader中，通过改变mfcc提取参数来对齐音频和视频的长度，那么为什么不预先将video转换成25fps格式，使用固定fps视频训练和使用匹配fps视频测试，这样准确率是否会更高

**Comment by TaoRuijie** [comment]
因为提供的标签换起来太麻烦了 所以没有做过这样的尝试

**Comment by wanghuii1** [comment]
谢谢回复，非常棒的工作！
Active speaker detection是当前连接speaker-related audio cues和visual cues的重要渠道之一。我能否将训练代码merge到[3D-Speaker](https://github.com/alibaba-damo-academy/3D-Speaker)中。

**Comment by TaoRuijie** [comment]
你好！抱歉才看到，可以的没问题，感谢3D-Speaker对于社区的贡献！
