### ISSUE TITLE
ONNX export issue

### ISSUE THREAD

**Issue by Leeviber** [TaoRuijie/TalkNet_ASD#8]
Hi author,

I successfully run you pretrain model on custom video and present really good performace !
when I tried to exported to ONNX model and run, it present some error which said `Try match Slice_Slice_704:out0 failed, catch exception!`

I think there is something wrong with my forward function as shown in below
`    
        def forward(self,audio,video):

        audio = audio.unsqueeze(1).transpose(2, 3)        
        audio = self.audioEncoder(audio)

        B, T, W, H = video.shape  
        video = video.view(B*T, 1, 1, W, H)
        video = (video / 255 - 0.4161) / 0.1688
        video = self.visualFrontend(video)
        video = video.view(B, T, 512)        
        video = video.transpose(1,2)     
        video = self.visualTCN(video)
        video = self.visualConv1D(video)
        video = video.transpose(1,2)

        audioEmbed = self.crossA2V(src = audio, tar = video)
        visualEmbed = self.crossV2A(src = video, tar = audio)      

        outsAV = torch.cat((audioEmbed,visualEmbed), 2)    
        outsAV = self.selfAV(src = outsAV, tar = outsAV)       
        outsAV = torch.reshape(outsAV, (-1, 256))

        outsAV = outsAV.squeeze(0)
        outsAV = self.FC(outsAV)

        return outsAV`
I am not sure this is correct, Is is possible provide the ONNX format pretrain model?

**Comment by TaoRuijie** [comment]
Thanks for your interest in our work! The forward function looks fine. You can also check the shape for each feature to further verify it.

Sorry, I am not familiar with ONNX, so I do not have the related format pre train model. Sorry about that.

Btw, that error looks like the version issue instead of the code issue (not very sure).

**Comment by Leeviber** [comment]
> Thanks for your interest in our work! The forward function looks fine. You can also check the shape for each feature to further verify it.
> 
> Sorry, I am not familiar with ONNX, so I do not have the related format pre train model. Sorry about that.
> 
> Btw, that error looks like the version issue instead of the code issue (not very sure).

Yeah, I figured it out. Unfortunately, the deploy of ONNX model is not support 3D conv&maxpooling. Thanks again, your works present the strongest performance I've ever tried.

**Comment by TaoRuijie** [comment]
Oh got it. Glad to know you are satisfied with the performance of our model. Good luck with your further research!
