### ISSUE TITLE
Warning while evaluating on test set

### ISSUE THREAD

**Issue by godatta** [TaoRuijie/TalkNet_ASD#9]
Hi,

I met with the following warning, while running your code with my model. I tried, but did not find any NFFT in your codebase. Is this something I can safely ignore, or can cause degradation in the test performance?

WARNING:root:frame length (556) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.

**Comment by TaoRuijie** [comment]
Hi, I once met this issue but I did not remember it very clearly. Here is my understanding:
1. Make sure the sampling rate of your wav file is 16k
2. Make sure all the wav files are normal. Some files are broken (like the size is only 256B). You can check the length of the wav file. The length ought to be at least 1s I think.

**Comment by godatta** [comment]
Thanks!
